Game logic
Adewunmi97/tic_tac_toe pull request #7
Opened 2020-10-08 15:49 UTC by Adewunmi97

-Suggested branch name game_logic.
-Added real logic for the game.

2020-10-08 20:20 UTC, SafaErden requested changes
## Status: Require changes ♻️

**Hi TEAM, your project is awesome. 👐 However, we need a little fix before we can proceed. Kindly find the comments below**
##

**REQUIRED CHANGES**

- [ ] The application should tell if there was a draw after players move, please fix it.

![image](https://user-images.githubusercontent.com/60184961/95506689-ec6b0080-09b8-11eb-949f-bb852191562d.png)

- [ ] All game-logic related resources (classes and/or modules) are kept in the `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

##

**NOTES**

Friendly reminder: Remember it's important to have a professional repo so you can increase your job opportunities. Please take a step back and read the lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.) Your commit messages contain typos and most of them are not descriptive enough. Please pay more attention when you are committing in your upcoming projects and use imperative tense for them.

##

**SUMMARY**

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

##

*Kindly make the changes and submit another code review once you are ready💪*

Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/) 🗨️

Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-10-08 20:20 UTC, SafaErden commented on lib/game.rb
> +  attr_accessor :player1, :player2, :board, :winning_combination
- [ ] The student uses attr_readers/attr_writers. Only uses attr_accessors if they really need it and must be aware that by using it they allow writing that property from outside the class. That variable can be set to anything. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

In this case, the winning_combination shouldn't be updated. So you should use attr_reader for it.

2020-10-08 20:20 UTC, SafaErden commented on bin/main.rb
> +  puts 'Enter Y or N'
- [ ] The game also ends when a user presses something other than 'N', so please fix the instructions.

2020-10-09 13:20 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-10-09 14:34 UTC, merged